// Protocol Buffers file for defining the messages and service used in a simple chat application based on gRPC.
// This file defines message types for users and chat messages, as well as a gRPC service for chat functionality.
// The chat service allows clients to get a list of users, send chat messages,
// and subscribe to a stream of incoming messages.
syntax = "proto3";

// Information about a user.
message User {
  string login = 1;
  string full_name = 2;
}

// Message definition for a chat message.
message Message {
  string from_user = 1;
  string to_user = 2;
  int64 timestamp = 3;
  string body = 4;
}

// List of users.
message GetUsersReply {
  repeated User users = 1;
}

// Request to send a chat message.
message SendMessageRequest {
  Message message = 1;
}

// Request to get a list of users.
message GetUsersRequest {}

// Response for sending a chat message.
message SendMessageReply {}

// Request to subscribe to a stream of chat messages.
message SubscribeRequest {
  string login = 1;
}

// ChatService provides RPC methods for chat functionality.
service ChatService {
  // Get a list of users.
  rpc GetUsers(GetUsersRequest) returns (GetUsersReply);

  // Send a chat message.
  rpc SendMessage(SendMessageRequest) returns (SendMessageReply);

  // Subscribe to a stream of chat messages.
  rpc Subscribe(SubscribeRequest) returns (stream Message);
}
